<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="w022581901803m-5.local" failures="1" tests="2" name="Gradle test" time="0.689" errors="0" timestamp="2020-07-13T17:50:58 JST">
  <testcase classname="TestNG" name="testNG" time="0.514"/>
  <testcase classname="TestNG" name="testNGFailure" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]
at TestNG.testNGFailure(TestNG.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 53 stack frames]]>
    </failure>
  </testcase> <!-- testNGFailure -->
</testsuite> <!-- Gradle test -->
